title = "Fission: Functions as a Service on Kubernetes"
baseURL = "http://fission.io/blog"
languageCode = "en-us"
theme = "ananke"

MetaDataFormat = "yaml"
DefaultContentLanguage = "en"
SectionPagesMenu = "main"
Paginate = 10 # this is set low for demonstrating with dummy content. Set to a higher number

enableRobotsTXT = true

[sitemap]
  changefreq = "monthly"
  priority = 0.5
  filename = "sitemap.xml"

[params]
  favicon = "" # TODO
  description = "Fission: FaaS for Kubernetes"
  twitter = "https://twitter.com/fissionio"
  github = "https://github.com/fission/fission"
  # choose a background color from any on this page: http://tachyons.io/docs/themes/skins/ and preface it with "bg-"
  background_color_class = "bg-navy"
  featured_image = "/images/blog-bg.png"
  recent_posts_number = 10
  env = "production"
